apiVersion: v1
kind: ConfigMap
metadata:
  name: bsc-rpc-config
  namespace: airflow
data:
  rpc_providers.json: |
    [
      {
        "name": "blockpi",
        "url_template": "https://bsc.blockpi.network/v1/rpc/{BLOCKPI_API_KEY}",
        "weight": 5,
        "enabled": true
      },
      {
        "name": "alchemy",
        "url_template": "https://bnb-mainnet.g.alchemy.com/v2/{ALCHEMY_API_KEY}",
        "weight": 1,
        "enabled": true
      }
    ]


