apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsc-logs-ingestion
  namespace: airflow
  labels:
    app: logs-ingestion
    chain: bsc
  annotations:
    reloader.stakater.com/auto: "true"
    
spec:
  replicas: 1
  # strategy:
  #   type: Recreate # 强制单实例 + 串行切换 （先 kill 旧 Pod，再建新 Pod）
  selector:
    matchLabels:
      app: logs-ingestion
      chain: bsc
  template:
    metadata:
      labels:
        app: logs-ingestion
        chain: bsc
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: ingestion
          image: evm-kafka-ingestion:0.3.0
          imagePullPolicy: IfNotPresent
          command: ["python", "web3_logs_ingestion.py"]

          # -----------------------------
          # Ingest runtime variables
          # -----------------------------
          env:
            - name: CHAIN
              value: "bsc"

            - name: JOB_MODE
              value: "backfill"
            # -----------------------------
            # Parallel execution (BATCH_SIZE = MAX_WORKERS * RANGE_SIZE)
            # RANGE_SIZE <= 2 for some public nodes (realtime setting: 8-16-2)
            # -----------------------------
            - name: MAX_WORKERS
              value: "8"

            - name: BATCH_SIZE
              value: "40"
            
            - name: RANGE_SIZE
              value: "5"

          # -----------------------------
          # Metrics endpoint
          # -----------------------------
          ports:
            - name: metrics
              containerPort: 8000

          # -----------------------------
          # Environment variables
          # - Secrets only (API keys)
          # -----------------------------
          envFrom:
            - secretRef:
                name: rpc-api-keys

          # -----------------------------
          # Volume mount (RPC config)
          # -----------------------------
          volumeMounts:
            - name: rpc-config
              mountPath: /etc/ingestion
              readOnly: true

          # -----------------------------
          # (Optional but recommended)
          # Resource limits
          # -----------------------------
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"

          # livenessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   failureThreshold: 3

          # readinessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   failureThreshold: 3
          
          # startupProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          #   failureThreshold: 30
          #   periodSeconds: 5

      # -----------------------------
      # Volumes
      # -----------------------------
      volumes:
        - name: rpc-config
          configMap:
            name: blockchain-rpc-config
