apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bsc-logs-ingestion
  namespace: prometheus
  labels:
    release: prometheus        # service discovery for prometheus
spec:
  namespaceSelector:
    matchNames:
      - airflow
  selector:
    matchLabels:
      app: bsc-logs-ingestion
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
