apiVersion: v1
kind: Service
metadata:
  name: bsc-ingestion-metrics
  namespace: airflow
  labels:
    app: bsc-logs-ingestion
spec:
  selector:
    app: bsc-logs-ingestion
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
