apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: logs-ingestion
  namespace: prometheus
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - airflow
  selector:
    matchLabels:
      app: logs-ingestion
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
