apiVersion: v1
kind: Service
metadata:
  name: logs-ingestion-metrics
  namespace: airflow
  labels:
    app: logs-ingestion
spec:
  selector:
    app: logs-ingestion
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
