apiVersion: v1
kind: Secret
metadata:
  name: rpc-api-keys
  namespace: airflow
type: Opaque
stringData:
  BLOCKPI_BSC_API_KEY: "xxxx"
  BLOCKPI_ETH_API_KEY: "yyyy"
  BLOCKPI_BASE_API_KEY: "zzzz"

  INFURA_ETH_API_KEY: "aaa"
  INFURA_BASE_API_KEY: "bbb"
