apiVersion: v1
kind: Service
metadata:
  name: erigon-bsc
  namespace: blockchain
spec:
  selector:
    app: erigon-bsc
  ports:
    - name: http
      port: 8545
      targetPort: 8545
    - name: ws
      port: 8546
      targetPort: 8546
    - name: metrics
      port: 6060
      targetPort: 6060
