apiVersion: batch/v1
kind: Job
metadata:
  name: eth-block-ingestion-backfill-2026-01-02-to-2026-01-02
  namespace: airflow
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: eth-backfill
        image: eth-backfill:0.1.3
        imagePullPolicy: IfNotPresent
        command: ["python", "eth_backfill_job.py"]
        env:
          - name: START_DATE
            value: "2026-01-02"
          - name: END_DATE
            value: "2026-01-02"
          - name: ETH_ETHERSCAN_API_KEY
            valueFrom:
              secretKeyRef:
                name: ETH_ETHERSCAN_API_KEY
                key: api_key
          - name: ETH_INFURA_RPC_URL
            valueFrom:
              secretKeyRef:
                name: eth-secrets
                key: ETH_INFURA_RPC_URL
