title: "K8s Data Platform"
subtitle: "Local Dev Dashboard"
logo: "./logo.png"

theme: default
color: slate

services:
  - name: "Observability"
    icon: "fas fa-chart-line"
    items:
      - name: "Prometheus"
        url: "http://localhost:9090"
        icon: "fas fa-chart-area"
        target: "_blank"

      - name: "Grafana"
        url: "http://localhost:3000"
        icon: "fas fa-chart-area"
        target: "_blank"

      # - name: "Kubernetes dashboard"
      #   url: "http://localhost:9092"
      #   icon: "fas fa-chart-area"
      #   target: "_blank"

      # - name: "Headlamp"
      #   url: "http://localhost:9093"
      #   icon: "fas fa-chart-area"
      #   target: "_blank"

  - name: "Orchestration"
    icon: "fas fa-project-diagram"
    items:
      - name: "Airflow"
        url: "http://localhost:8081"
        icon: "fas fa-network-wired"
        target: "_blank"

      - name: "Dagster"
        url: "http://localhost:8082"
        icon: "fas fa-wind"
        target: "_blank"

  - name: "Streaming"
    icon: "fas fa-stream"
    items:
      - name: "Redpanda Console"
        url: "http://localhost:8086"
        icon: "fas fa-fish"
        target: "_blank"

  - name: "Object Storage "
    icon: "fas fa-stream"
    items:
      - name: "Minio"
        url: "http://localhost:9001" # minioadmin/minioadmin
        icon: "fas fa-fish"
        target: "_blank"

  - name: "Compute"
    icon: "fas fa-microchip"
    items:
      - name: "Jupyter Notebook"
        url: "http://127.0.0.1:8888/lab?token=53e3fb899dc4182411d79ce62da1c4a6dd5d4dad464c6eb1" # login pod with command "jupyter server list"
        icon: "fas fa-book"
        target: "_blank"
