[project]
name = "eth-ingestion"
version = "0.1.0"
description = "Ingest Ethereum blocks and publish to Kafka"
requires-python = ">=3.11"
dependencies = [
    "confluent-kafka>=2.12.2",
    "web3>=7.14.0"
]
